# Generated by Django 2.1 on 2018-08-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('britecore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdatafield',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
